# Generated by Django 5.0.4 on 2024-04-27 14:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("drone_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="usr",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("usr_name", models.CharField(max_length=64)),
                ("password", models.CharField(max_length=64)),
            ],
        ),
    ]
